version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: projectdb
      MYSQL_ROOT_PASSWORD: master
      MYSQL_USER: martim
      MYSQL_PASSWORD: Martim123
    networks:
      - mysqlcomposenetwork
    volumes:
      - ./data:/data
    ports:
      - 100:100
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminercontainer
    ports:
      - 8080:8080
    networks:
      - mysqlcomposenetwork
    depends_on:
      - db
  app:
    container_name: myapp
    networks:
      - mysqlcomposenetwork
    build: ./
    depends_on:
      - db
      - adminercontainer
    ports:
    - 5001:5000
  

networks: 
  mysqlcomposenetwork:
    driver: bridge